In [1]:
import numpy as np

In [4]:
l=[1,2,3,4,5]

In [5]:
arr = np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(1)

array(1)

In [9]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
arr.ndim

1

In [12]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [13]:
arr1.ndim

2

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [17]:
mat = np.matrix(1)

In [18]:
np.asanyarray(1)

array(1)

In [26]:
np.asanyarray(mat)

matrix([[1]])

In [32]:
arr

array([100,   2,   3,   4,   5])

In [33]:
a = arr

In [29]:
arr

array([100,   2,   3,   4,   5])

In [30]:
arr[0]=100

In [35]:
a = arr

In [36]:
a

array([100,   2,   3,   4,   5])

In [37]:
arr

array([100,   2,   3,   4,   5])

In [39]:
arr[0] =100

In [40]:
arr

array([100,   2,   3,   4,   5])

In [41]:
a

array([100,   2,   3,   4,   5])

In [43]:
b = np.copy(arr)

In [45]:
b[0] =123

In [46]:
b

array([123,   2,   3,   4,   5])

In [47]:
arr

array([100,   2,   3,   4,   5])

In [49]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [48]:
np.fromfunction(lambda i,j : i**j ,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [51]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [52]:
iterable = (i*i for i in range(5))

In [53]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [56]:
np.fromstring('23 34 45',sep =' ')

array([23., 34., 45.])

In [57]:
np.fromstring('23 ,34 ,45 ',sep =',')

array([23., 34., 45.])

In [58]:
arr

array([100,   2,   3,   4,   5])

In [59]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [60]:
arr.ndim

1

In [61]:
arr1.ndim

2

In [62]:
arr.size

5

In [63]:
arr1.size

6

In [64]:
arr.shape

(5,)

In [65]:
arr1.shape

(2, 3)

In [66]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [67]:
arr.dtype

dtype('int64')

In [68]:
arr1.dtype

dtype('int64')